default.nix

It was a dangling symlink in the build.

🐛 Fix changelog in the docs

---

CHANGELOG.md
languages/python/package.nix

Python does not use mkDerivation, it uses buildPythonPackage so
shellCommands are not propagated.
Also allow target setup for python to be a complete target setup and not
only override individual parts of it.

🐛 Fix python shellCommands and targetSetup

---

CHANGELOG.md
languages/python/package.nix
targetsetup.nix

Also make the nix name of the targetSetup derivation more readable.
The variables were just exported too late.

💄 Make targetSetup's file tree view show varaibles

---

CHANGELOG.md
targetsetup.nix

Can now be any kind of file (-e instead of -f) and can use variables
with the substitute syntax (@variable@) like the template files.

⚡ Make targetSetup better with marker files

---

CHANGELOG.md
default.nix

Extensions can now depend on `components` to get a set of all compoents,
just like components themselves can.

⚡ Add components (all components) to extensions

---

CHANGELOG.md
default.nix
languages/rust/default.nix

This reverts commit af4a8a02b63d8733f3b6c0a5db69d5bb3bf6de34. This
solution never really worked. Now checks could NEVER be run, because
`stdenv.mkDerivation` sets doCheck to what is sent in or false. So
we can never know if the user set the attribute or nixpkgs did.

🐛 Revert "🐛 Fix doCheck not skipping checks"

---

CHANGELOG.md
documentation/mdbook.nix
documentation/mkdocs.nix
languages/python/package.nix
languages/rust/package.nix
languages/terraform/default.nix
shell-commands.nix
shells.nix

Also silence the sourcing of the shellCommands' environment.
When entering a shell, list the commands and their description. Example:
```
shellCOmmands = {
command-name = {
script = "code...";
description = ''
Very good description.
Can be multi line
'';
args = "-h --help";
};
secret-command-name = {
script = "code...";
show = false;
};
simple-command = "code...";
};
```

✨ 📚 Show shellCommands and their description

---

CHANGELOG.md
examples/documentation/client/awesome_client/main.py
languages/python/docs.nix

When generating API docs for Python code with Sphinx, enable the
Napoleon extension that provides support for parsing Google-style
docstrings.

⚡ Support Google style docstrings for Sphinx

---

CHANGELOG.md
shells.nix

Docs are derivations in derivations, not derivations in components so
they are missed by collectComponentsRecursive nad did not get any
shells. Now we add on shells for them specifically and add a warning
that the `docs` shell itself it not valid since it's just the
symlinkJoin without anything useful.
Fixes #281

🐛 Fix shells for docs

---

CHANGELOG.md

6.2.0 was released by cherry picking commits but skipping the breaking
changes of tonic and prost-build.

📚 Update changelog with backport release

---

CHANGELOG.md
languages/terraform/default.nix

The deploy phase would try to make environment variables out of the set
which it can't.

🐛 Fix shellCommands for terraform components

---

.github/workflows/setup/setup-builders-ssh.sh
CHANGELOG.md
ci/shellcheck.bash
default.nix
languages/rust/protobuf/compiler/changeTonicBuildVersion.sh

Use shfmt for finding shell scripts, it is better and faster than the
find + function.

⚡ 🐎 Make ci shellcheck faster and more accurate

---

CHANGELOG.md
documentation/default.nix
documentation/mdbook.nix
documentation/mkdocs.nix
languages/python/component-template/setup.py
languages/python/default.nix
languages/python/package.nix

Unit tests runs on the source so there's no need to include the tests
folder in the wheel. Nix already strips it from the package. Having all
packages install a tests folder in site-packages will just override each
other.
We generate the tests folder so it seems nice to also be the ones to
exclude it.
Note that this is just the template for new components and does not
affect existing components.

⚡ Don't include the tests folder in python wheels

---

CHANGELOG.md
languages/python/default.nix

Some python packages in nixpkgs are not discoverable by pip (missing installinfo/egg_info) which causes problems for dependencies specified in `install_requires`. This commit makes Python work more akin to C++, where dependencies are specified once in Nix, to make sure they are present at build time and once in CMake/Make to actually depend on them. The python equivalent would be Nix to ensure prescence and `setup.py` to declare usage. This way of solving the problem also preserves the validity of the packages as normal Python packages.

⚡ 🐛 💎 Fix nix Python dependencies, 🍒 from in 6.3.0

---

CHANGELOG.md
documentation/mdbook-run.bash
documentation/mdbook.nix
shell-commands.nix
shells.nix

Run the expected hooks on build and install and let users extend buildInputs (when switching to nativeBuildInputs). Shadowed the run shellCommand with a shell function, this is so a trap can be defined in the shell to shut down mdbook when exiting the shell.
~If someone has a smart idea of how to use the shell command I'm all ears. Problem with just putting it there is that mdbook is started in the background from the shell command program, so the trap would either run to early (when `run` finishes) or not at all. Kept the shellCommand to get the printed description.~

⚡ Make mdbook more extendable and run better

---

CHANGELOG.md
shells.nix

When switching from builtins.abort to a shell that prints and exits the echo command was omitted resulting in the shell trying to execute the text as code.

🐛 Fix shell text on missing target

---

CHANGELOG.md
component.nix
default.nix

Make suer component sets do not get special treatment for targets
`deployment` and `docs`. It does not make sense for them to have any of those.

🐛 Fix deployment for component sets

---

CHANGELOG.md
component.nix
test/components.nix

collectComponentsRecursive and mapComponentsRecursive ignored component-set type which was not wanted. Now it goes through those sets.

🐛 ⚡ Fix comprecurse througf comp sets

---

CHANGELOG.md
component.nix

In order to speed up project evaluation, attributes can now be put in passthru on the component and those are not added to the linkFarm. Also added a commit which changes order of precedence of the linkFarm vs user attributes.

Linkfarm updates

---

CHANGELOG.md
component.nix

override didn't combine the old input with the new, it was just an alias for calling the original function.

🐛 Fix override on component

---

CHANGELOG.md
ci/shellcheck

Default IFS splits on any whitespace character, <<< would split on space as well as newline.

🐛 Fix shellcheck not handling spaces in file names

---

CHANGELOG.md
default.nix

stdenv.mkDerivation can take pname and version to construct name, lets not block anyone using base.mkDerivation from doing the same. Added a custom assert message because the message from the nested functions inside pkgs becomes a bit confusing.

🐛 Make base.mkDerivation take pname + version

---

CHANGELOG.md
shells.nix

Only use it to generate warning shells for missing/bad targets. This makes shells a bit simpler and avoids unnecessary and confusing extra steps with unexpected consequences.

🔨 Don't use mkShell for component's shells

---

.github/workflows/checks.yml
CHANGELOG.md
ci/actionlint
ci/check
ci/default.nix
ci/nixfmt
ci/nixlint
ci/shellcheck
component.nix
default.nix
documentation/default.nix
examples/dependencies/child/flake.lock
examples/dependencies/child/flake.nix
examples/dependencies/father/project.nix
examples/documentation/flake.lock
examples/documentation/flake.nix
examples/hello/clients/hello/hello.nix
examples/hello/flake.lock
examples/hello/flake.nix
flake.lock
flake.nix
nixpkgs.nix
shell-commands.nix
shells.nix
target-setup/default.nix
test/components.nix

- Change linter from nix-lint to statix since the former is broken in 23.11 and seems somewhat unmaintained. Fix all lints as well.

✨ Add support for nixpkgs up to 23.11

---

CHANGELOG.md
ci/default.nix
ci/nixfmt

If $nixFiles were expressed as relative to the root of the project, nixfmt would fail when ran from a sub directory. Now cd to the root first which will work for both relative and absolute paths.
Since nix (and thus we) have not committed to using flakes this instead uses git to find the root of the project.

🐛 Make checks.nixfmt work from everywhere
